# Generated by Django 5.1.6 on 2025-03-14 12:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.TextField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('physician_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField(null=True)),
                ('add', models.CharField(max_length=500)),
                ('phone', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateTimeField()),
                ('time_of_appointment', models.TimeField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('appointment_answer', models.TextField(blank=True, null=True)),
                ('encounter_status', models.BooleanField(default=False)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enc_date', models.DateField(default=datetime.date.today)),
                ('enc_patient_query', models.TextField(blank=True, max_length=550, null=True)),
                ('enc_physician_finding', models.TextField(blank=True, max_length=1000, null=True)),
                ('enc_prescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('enc_lab_test', models.TextField(blank=True, max_length=1000, null=True)),
                ('enc_diet', models.TextField(blank=True, max_length=550, null=True)),
                ('enc_allergy', models.TextField(blank=True, max_length=500, null=True)),
                ('enc_remark', models.TextField(max_length=550)),
                ('enc_time_start', models.TimeField()),
                ('enc_time_end', models.TimeField()),
                ('enc_answer', models.TextField(blank=True, null=True)),
                ('enc_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.appointment')),
                ('enc_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('enc_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.patient')),
            ],
        ),
    ]
